When Commons-logging or Log4J is not in the classpath, tries to throw a checked ClassNotFoundException early instead of a unchecked NoClassDefFoundError late (when a message is first logged, which may be long after the setLoggerFactory(...) call).
git-svn-id: https://svn.osgeo.org/geotools/geotools/trunk@27890 e5c1c795-43da-0310-a71f-fac65c449510